/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_PlanarN_3_Snum.c
 *
 * Code generation for function 'get_PlanarN_3_Snum'
 *
 */

/* Include files */
#include "get_PlanarN_3_Snum.h"

/* Function Definitions */
void get_PlanarN_3_Snum(double in1[3], double in2[3], double S_tmp[9], double* S, double* C)
{
  double t10;
  double t11;
  double t14;
  double t15;
  double t19;
  double t2;
  double t20;
  double t21;
  double t23;
  double t27;
  double t29;
  double t3;
  double t30;
  double t30_tmp;
  double t36;
  double t38;
  double t39;
  double t4;
  double t41;
  double t47;
  double t5;
  double t6;
  double t7;
  /* get_PlanarN_3_Snum */
  /*     S_tmp = get_PlanarN_3_Snum(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     22-Jan-2025 16:27:54 */
  t2 = C[1]; //cos(in1[1]);
  t3 = C[2]; //cos(in1[2]);
  t4 = S[1]; //sin(in1[1]);
  t5 = S[2]; //sin(in1[2]);
  t6 = t2 * 0.22;
  t7 = t3 * 0.22;
  t11 = t4 * t5 * 0.22;
  t29 = t2 * t5 * 0.05749405662;
  t30_tmp = t3 * t4;
  t30 = t30_tmp * 0.05749405662;
  t10 = t4 * t7;
  t14 = t3 * (t6 + 0.22);
  t15 = t5 * (t6 + 0.22);
  t19 = t5 * t6 + t10;
  t20 = t3 * t6 - t11;
  t21 = t10 + t15;
  t36 = (-t11 + t14) + 0.151149;
  t10 = t11 - t14;
  t23 = t3 * t21 * 0.38038;
  t38 = t5 * t36 * 0.38038;
  t39 = t3 * t5 * 0.1673672 - t5 * (t7 + 0.151149) * 0.76076;
  t11 = t21 * (t7 + 0.151149) * 1.729;
  t27 = t5 * t10 * 0.38038;
  t41 = in2[1] * t39;
  t47 = t21 * t10 * 3.458 + t21 * t36 * 3.458;
  t14 = ((t2 * t4 * 0.1673672 - t4 * (t6 + 0.151149) * 0.76076) +
         t20 * t21 * 3.458) -
        t19 * t36 * 3.458;
  t3 = ((((-t23 + t27) + t29) + t30) + t38) + t11;
  t21 = in2[0] * t47;
  t36 = in2[0] * t14;
  t10 = ((((t23 - t27) + t29) + t30) - t38) - t11;
  t11 = in2[0] * t10;
  S_tmp[0] = -in2[2] * t47 + in2[1] * t14;
  S_tmp[1] = -t36 + in2[2] * t10;
  S_tmp[2] = t21 - in2[1] * t10;
  S_tmp[3] = (t36 - in2[2] * t3) -
             in2[1] * ((t4 * 0.11498811324 - t5 * t20 * 0.76076) +
                       t19 * (t7 + 0.151149) * 3.458);
  S_tmp[4] = in2[2] * t39;
  S_tmp[5] = -t41 - t11;
  S_tmp[6] = (-t21 - in2[1] * t3) -
             in2[2] * (t15 * 0.522673242 + t30_tmp * 0.11498811324);
  S_tmp[7] = (t41 + t11) - in2[2] * t5 * 0.11498811324;
  S_tmp[8] = 0.0;
}

/* End of code generation (get_PlanarN_3_Snum.c) */
