/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_PlanarN_5_Mnum.c
 *
 * Code generation for function 'get_PlanarN_5_Mnum'
 *
 */

/* Include files */
#include "get_PlanarN_5_Mnum.h"

/* Function Definitions */
void get_PlanarN_5_Mnum(double in1[5], double M_INERTIA[25], double* S, double* C)
{
  double t10;
  double t102;
  double t103;
  double t105;
  double t109;
  double t11;
  double t12;
  double t13;
  double t17_tmp;
  double t18_tmp;
  double t2;
  double t26;
  double t27;
  double t28;
  double t3;
  double t32;
  double t33;
  double t34;
  double t37;
  double t38;
  double t4;
  double t41_tmp;
  double t42_tmp;
  double t43;
  double t44;
  double t5;
  double t56;
  double t6;
  double t68;
  double t69;
  double t7;
  double t70;
  double t8;
  double t80_tmp;
  double t81;
  double t86;
  double t9;
  double t96;
  /* get_PlanarN_5_Mnum */
  /*     M_INERTIA = get_PlanarN_5_Mnum(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     22-Jan-2025 13:37:45 */
  t2 = C[1]; //cos(in1[1]);
  t3 = C[2]; //cos(in1[2]);
  t4 = C[3]; //cos(in1[3]);
  t5 = C[4]; //cos(in1[4]);
  t6 = S[1]; //sin(in1[1]);
  t7 = S[2]; //sin(in1[2]);
  t8 = S[3]; //sin(in1[3]);
  t9 = S[4]; //sin(in1[4]);
  t10 = t2 * 0.22;
  t11 = t3 * 0.22;
  t12 = t4 * 0.22;
  t13 = t5 * 0.22;
  t17_tmp = t6 * t7;
  t18_tmp = t7 * t8;
  t56 = t5 * 0.11498811324;
  t26 = t3 * (t10 + 0.22);
  t27 = t4 * (t11 + 0.22);
  t28 = t5 * (t12 + 0.22);
  t32 = t6 * t11 + t7 * (t10 + 0.22);
  t33 = t7 * t12 + t8 * (t11 + 0.22);
  t34 = t8 * t13 + t9 * (t12 + 0.22);
  t41_tmp = -(t17_tmp * 0.22) + t26;
  t42_tmp = -(t18_tmp * 0.22) + t27;
  t81 = t8 * t9;
  t68 = (-(t81 * 0.22) + t28) + 0.151149;
  t37 = t8 * t32;
  t38 = t9 * t33;
  t43 = t4 * (t41_tmp + 0.22);
  t44 = t5 * (t42_tmp + 0.22);
  t102 = (-(t81 * 0.11498811324) + t28 * 0.522673242) + 0.407701537855058;
  t69 = t4 * t32 + t8 * (t41_tmp + 0.22);
  t70 = t5 * t33 + t9 * (t42_tmp + 0.22);
  t109 = ((t9 * t34 * 0.76076 + t4 * 0.11498811324) +
          (t13 + 0.151149) * t68 * 3.458) +
         0.736401537855058;
  t28 = t9 * t69;
  t80_tmp = -t37 + t43;
  t86 = (-t38 + t44) + 0.151149;
  t81 = t5 * (t80_tmp + 0.22);
  t105 = (-(t38 * 0.522673242) + t44 * 0.522673242) + 0.407701537855058;
  t96 = t5 * t69 + t9 * (t80_tmp + 0.22);
  t103 = (-t28 + t81) + 0.151149;
  t5 =
      (((-(t18_tmp * 0.11498811324) + t27 * 0.522673242) + t9 * t70 * 0.76076) +
       (t13 + 0.151149) * t86 * 3.458) +
      0.736401537855058;
  t44 = ((((t8 * t33 * 0.76076 + t3 * 0.11498811324) + t34 * t70 * 3.458) +
          (t12 + 0.151149) * (t42_tmp + 0.151149) * 3.458) +
         t68 * t86 * 3.458) +
        1.0651015378550579;
  t38 = (-(t28 * 0.522673242) + t81 * 0.522673242) + 0.407701537855058;
  t4 = (((-(t37 * 0.522673242) + t43 * 0.522673242) + t9 * t96 * 0.76076) +
        (t13 + 0.151149) * t103 * 3.458) +
       0.736401537855058;
  t81 = (((((-(t17_tmp * 0.11498811324) + t26 * 0.522673242) +
            t8 * t69 * 0.76076) +
           (t12 + 0.151149) * (t80_tmp + 0.151149) * 3.458) +
          t34 * t96 * 3.458) +
         t68 * t103 * 3.458) +
        1.0651015378550579;
  t28 = ((((((t7 * t32 * 0.76076 + t2 * 0.11498811324) + t33 * t69 * 3.458) +
            (t11 + 0.151149) * (t41_tmp + 0.151149) * 3.458) +
           (t42_tmp + 0.151149) * (t80_tmp + 0.151149) * 3.458) +
          t70 * t96 * 3.458) +
         t86 * t103 * 3.458) +
        1.3938015378550579;
  M_INERTIA[0] = (((((((t6 * t6 * 0.1673672 + t32 * t32 * 3.458) +
                       (t41_tmp + 0.151149) * (t41_tmp + 0.151149) * 3.458) +
                      t69 * t69 * 3.458) +
                     (t80_tmp + 0.151149) * (t80_tmp + 0.151149) * 3.458) +
                    t96 * t96 * 3.458) +
                   t103 * t103 * 3.458) +
                  (t10 + 0.151149) * (t10 + 0.151149) * 3.458) +
                 1.7225015378550581;
  M_INERTIA[1] = t28;
  M_INERTIA[2] = t81;
  M_INERTIA[3] = t4;
  M_INERTIA[4] = t38;
  M_INERTIA[5] = t28;
  M_INERTIA[6] = (((((t7 * t7 * 0.1673672 + t33 * t33 * 3.458) +
                     (t11 + 0.151149) * (t11 + 0.151149) * 3.458) +
                    (t42_tmp + 0.151149) * (t42_tmp + 0.151149) * 3.458) +
                   t70 * t70 * 3.458) +
                  t86 * t86 * 3.458) +
                 1.3938015378550579;
  M_INERTIA[7] = t44;
  M_INERTIA[8] = t5;
  M_INERTIA[9] = t105;
  M_INERTIA[10] = t81;
  M_INERTIA[11] = t44;
  M_INERTIA[12] = (((t8 * t8 * 0.1673672 + t34 * t34 * 3.458) +
                    (t12 + 0.151149) * (t12 + 0.151149) * 3.458) +
                   t68 * t68 * 3.458) +
                  1.0651015378550579;
  M_INERTIA[13] = t109;
  M_INERTIA[14] = t102;
  M_INERTIA[15] = t4;
  M_INERTIA[16] = t5;
  M_INERTIA[17] = t109;
  M_INERTIA[18] =
      (t9 * t9 * 0.1673672 + (t13 + 0.151149) * (t13 + 0.151149) * 3.458) +
      0.736401537855058;
  M_INERTIA[19] = t56 + 0.407701537855058;
  M_INERTIA[20] = t38;
  M_INERTIA[21] = t105;
  M_INERTIA[22] = t102;
  M_INERTIA[23] = t56 + 0.407701537855058;
  M_INERTIA[24] = 0.407701537855058;
}

/* End of code generation (get_PlanarN_5_Mnum.c) */
