/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_PlanarN_5_Snum.c
 *
 * Code generation for function 'get_PlanarN_5_Snum'
 *
 */

/* Include files */
#include "get_PlanarN_5_Snum.h"

/* Function Definitions */
void get_PlanarN_5_Snum(double in1[5], double in2[5], double S_tmp[25], double* S, double* C)
{
  double b_t140_tmp;
  double b_t256_tmp;
  double t10;
  double t100;
  double t100_tmp;
  double t101;
  double t102;
  double t102_tmp;
  double t103;
  double t104;
  double t104_tmp;
  double t109;
  double t11;
  double t110;
  double t12;
  double t13;
  double t131;
  double t132;
  double t133;
  double t135;
  double t136;
  double t137;
  double t138;
  double t140_tmp;
  double t143;
  double t143_tmp;
  double t144;
  double t145;
  double t151;
  double t152;
  double t153;
  double t154;
  double t159;
  double t160_tmp;
  double t161;
  double t163;
  double t171;
  double t172;
  double t174;
  double t177;
  double t178;
  double t179;
  double t18;
  double t180;
  double t183;
  double t189;
  double t189_tmp;
  double t190;
  double t190_tmp;
  double t191;
  double t2;
  double t20;
  double t202;
  double t203;
  double t206;
  double t207;
  double t208;
  double t209;
  double t217;
  double t219;
  double t22;
  double t221;
  double t222;
  double t223;
  double t226;
  double t229;
  double t23;
  double t232;
  double t239;
  double t24;
  double t240;
  double t241;
  double t242;
  double t243;
  double t245;
  double t246;
  double t249;
  double t25;
  double t251;
  double t253;
  double t256_tmp;
  double t259;
  double t260;
  double t261_tmp;
  double t262;
  double t268;
  double t271;
  double t272;
  double t273;
  double t276;
  double t280;
  double t285;
  double t285_tmp;
  double t291;
  double t293;
  double t298;
  double t299;
  double t3;
  double t306;
  double t307;
  double t308;
  double t311;
  double t314;
  double t314_tmp;
  double t315;
  double t317;
  double t32;
  double t33;
  double t331;
  double t332;
  double t333;
  double t337;
  double t338;
  double t34;
  double t341;
  double t342;
  double t343;
  double t344;
  double t349;
  double t349_tmp;
  double t35;
  double t353;
  double t357;
  double t36;
  double t37;
  double t4;
  double t45;
  double t46;
  double t47;
  double t48;
  double t49;
  double t5;
  double t50;
  double t51;
  double t52;
  double t57;
  double t58;
  double t6;
  double t61;
  double t62;
  double t63;
  double t64;
  double t65;
  double t66;
  double t67;
  double t68;
  double t7;
  double t77_tmp;
  double t78_tmp;
  double t8;
  double t83;
  double t84;
  double t86;
  double t87;
  double t9;
  double t96;
  double t99;
  /* get_PlanarN_5_Snum */
  /*     S_tmp = get_PlanarN_5_Snum(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     22-Jan-2025 13:37:49 */
  t2 = C[1]; //cos(in1[1]);
  t3 = C[2]; //cos(in1[2]);
  t4 = C[3]; //cos(in1[3]);
  t5 = C[4]; //cos(in1[4]);
  t6 = S[1]; //sin(in1[1]);
  t7 = S[2]; //sin(in1[2]);
  t8 = S[3]; //sin(in1[3]);
  t9 = S[4]; //sin(in1[4]);
  t10 = t2 * 0.22;
  t11 = t3 * 0.22;
  t12 = t4 * 0.22;
  t13 = t5 * 0.22;
  t23 = t6 * t7 * 0.22;
  t24 = t7 * t8 * 0.22;
  t25 = t8 * t9 * 0.22;
  t99 = t2 * t7 * 0.05749405662;
  t100_tmp = t3 * t6;
  t100 = t100_tmp * 0.05749405662;
  t101 = t3 * t8 * 0.05749405662;
  t102_tmp = t4 * t7;
  t102 = t102_tmp * 0.05749405662;
  t103 = t4 * t9 * 0.05749405662;
  t104_tmp = t5 * t8;
  t104 = t104_tmp * 0.05749405662;
  t18 = t6 * t11;
  t20 = t7 * t12;
  t22 = t8 * t13;
  t32 = t3 * (t10 + 0.22);
  t33 = t4 * (t11 + 0.22);
  t34 = t5 * (t12 + 0.22);
  t35 = t7 * (t10 + 0.22);
  t36 = t8 * (t11 + 0.22);
  t37 = t9 * (t12 + 0.22);
  t45 = t7 * t10 + t18;
  t46 = t8 * t11 + t20;
  t47 = t9 * t12 + t22;
  t48 = t3 * t10 - t23;
  t49 = t4 * t11 - t24;
  t50 = t5 * t12 - t25;
  t51 = t4 * t45;
  t52 = t5 * t46;
  t57 = t8 * t48;
  t58 = t9 * t49;
  t61 = t18 + t35;
  t62 = t20 + t36;
  t63 = t22 + t37;
  t77_tmp = -t23 + t32;
  t78_tmp = -t24 + t33;
  t131 = (-t25 + t34) + 0.151149;
  t64 = t23 - t32;
  t65 = t24 - t33;
  t66 = t25 - t34;
  t67 = t4 * t61;
  t68 = t5 * t62;
  t18 = t8 * t61;
  t22 = t9 * t62;
  t20 = t4 * (t77_tmp + 0.22);
  t23 = t5 * (t78_tmp + 0.22);
  t83 = t8 * (t77_tmp + 0.22);
  t84 = t9 * (t78_tmp + 0.22);
  t86 = t4 * t62 * 0.38038;
  t87 = t5 * t63 * 0.38038;
  t109 = t51 + t57;
  t110 = t52 + t58;
  t132 = t51 * 0.261336621;
  t133 = t52 * 0.261336621;
  t135 = t57 * 0.261336621;
  t136 = t58 * 0.261336621;
  t140_tmp = t8 * t45 - t4 * t48;
  b_t140_tmp = t8 * t140_tmp;
  t143_tmp = t9 * t46 - t5 * t49;
  t143 = t9 * t143_tmp * 0.38038;
  t171 = t7 * (t77_tmp + 0.151149) * 0.38038;
  t172 = t8 * (t78_tmp + 0.151149) * 0.38038;
  t25 = t9 * t131 * 0.38038;
  t174 = t5 * t9 * 0.1673672 - t9 * (t13 + 0.151149) * 0.76076;
  t179 = t61 * (t11 + 0.151149) * 1.729;
  t180 = t62 * (t12 + 0.151149) * 1.729;
  t34 = t63 * (t13 + 0.151149) * 1.729;
  t24 = t8 * t64;
  t33 = t9 * t65;
  t96 = t8 * t65 * 0.38038;
  t51 = t9 * t66 * 0.38038;
  t32 = t5 * t109;
  t151 = t67 + t83;
  t152 = t68 + t84;
  t153 = t67 * 0.261336621;
  t154 = t68 * 0.261336621;
  t178 = in2[3] * t174;
  t189_tmp = t18 - t20;
  t189 = t8 * t189_tmp * 0.38038;
  t190_tmp = t22 - t23;
  t190 = t9 * t190_tmp * 0.38038;
  t208 = (t12 + 0.151149) * t109 * 1.729;
  t209 = (t13 + 0.151149) * t110 * 1.729;
  t222 = t62 * t189_tmp * 1.729;
  t223 = t63 * t190_tmp * 1.729;
  t137 = t18 + t4 * t64;
  t138 = t22 + t5 * t65;
  t159 = -t18 + t20;
  t160_tmp = -t22 + t23;
  t161 = t24 * 0.261336621;
  t57 = t33 * 0.261336621;
  t163 = t5 * t151;
  t23 = t9 * t151;
  t183 = t4 * t151 * 0.38038;
  t58 = t5 * t152 * 0.38038;
  t191 = t32 * 0.261336621;
  t202 = t49 * t151 * 1.729;
  t203 = t50 * t152 * 1.729;
  t217 = t65 * t151 * 1.729;
  t219 = t66 * t152 * 1.729;
  t221 = t32 + -t9 * t140_tmp;
  t232 = (t12 + 0.151149) * t151 * 1.729;
  t52 = (t13 + 0.151149) * t152 * 1.729;
  t245 = (t78_tmp + 0.151149) * t151 * 1.729;
  t246 = t131 * t152 * 1.729;
  t256_tmp = t9 * t109 + t5 * t140_tmp;
  b_t256_tmp = t63 * t256_tmp;
  t271 = t63 * t66 * 3.458 + t63 * t131 * 3.458;
  t307 = ((t4 * t8 * 0.1673672 - t8 * (t12 + 0.151149) * 0.76076) +
          t50 * t63 * 3.458) -
         t47 * t131 * 3.458;
  t331 = ((((-t87 + t51) + t103) + t104) + t25) + t34;
  t144 = t67 - t24;
  t145 = t68 - t33;
  t32 = t9 * t137;
  t206 = t62 * t137 * 1.729;
  t207 = t63 * t138 * 1.729;
  t226 = t163 * 0.261336621;
  t253 = t163 + -t9 * t189_tmp;
  t262 = (t13 + 0.151149) * t221 * 1.729;
  t273 = in2[2] * t271;
  t276 = t131 * t221 * 1.729;
  t285_tmp = t23 + t5 * t189_tmp;
  t285 = t63 * t285_tmp * 1.729;
  t306 = t152 * t285_tmp * 1.729;
  t308 = in2[2] * t307;
  t332 = ((((t87 - t51) + t103) + t104) - t25) - t34;
  t20 = t5 * t144;
  t18 = t5 * (t159 + 0.22);
  t177 = t9 * (t159 + 0.22);
  t4 = t32 * 0.261336621;
  t229 = t8 * (t159 + 0.151149) * 0.38038;
  t22 = t9 * (t160_tmp + 0.151149) * 0.38038;
  t239 = t46 * (t159 + 0.151149) * 1.729;
  t240 = t47 * (t160_tmp + 0.151149) * 1.729;
  t242 = (t78_tmp + 0.151149) * t144 * 1.729;
  t243 = t131 * t145 * 1.729;
  t249 = t62 * (t159 + 0.151149) * 1.729;
  t251 = t63 * (t160_tmp + 0.151149) * 1.729;
  t299 = t131 * t253 * 1.729;
  t315 = (t160_tmp + 0.151149) * t253 * 1.729;
  t333 = in2[2] * t332;
  t87 = t20 * 0.261336621;
  t241 = t5 * t137 + t9 * t144;
  t259 = t163 + t177;
  t261_tmp = -t23 + t18;
  t23 -= t18;
  t272 = t9 * t23 * 0.38038;
  t33 = t63 * t23 * 1.729;
  t311 = t152 * t23 * 1.729;
  t314_tmp = t32 - t20;
  t314 = (t160_tmp + 0.151149) * t314_tmp * -1.729;
  t337 = ((t62 * t65 * 3.458 + t62 * (t78_tmp + 0.151149) * 3.458) +
          t138 * t152 * 3.458) +
         t145 * (t160_tmp + 0.151149) * 3.458;
  t341 = ((((-t154 + t57) - t58) + t190) + t22) + t52;
  t342 = ((((t154 - t57) - t58) + t190) + t22) + t52;
  t344 = ((((t133 + t136) + t219) + t223) + t246) + t251;
  t353 = ((((((((((-t86 + t96) + t101) + t102) + t143) + t172) + t180) - t203) +
            t207) +
           t209) +
          t240) +
         t243;
  t260 = t9 * t241 * 0.38038;
  t268 = t5 * t259 * 0.38038;
  t280 = t50 * t259 * 1.729;
  t18 = t66 * t259 * 1.729;
  t293 = (t13 + 0.151149) * t259 * 1.729;
  t25 = t259 * t143_tmp * 1.729;
  t34 = t152 * t241 * 1.729;
  t20 = t131 * t259 * 1.729;
  t32 = t138 * t259 * 1.729;
  t66 = t259 * t190_tmp * 1.729;
  t5 = (t160_tmp + 0.151149) * t259 * 1.729;
  t338 = in2[1] * t337;
  t343 = in2[1] * t341;
  t291 = t9 * (t261_tmp + 0.151149) * 0.38038;
  t298 = t47 * (t261_tmp + 0.151149) * 1.729;
  t22 = t63 * (t261_tmp + 0.151149) * 1.729;
  t51 = t110 * (t261_tmp + 0.151149) * 1.729;
  t24 = t145 * (t261_tmp + 0.151149) * 1.729;
  t317 = t152 * (t261_tmp + 0.151149) * 1.729;
  t103 = t259 * t23 * 3.458 + t259 * (t261_tmp + 0.151149) * 3.458;
  t349_tmp = t9 * t189_tmp;
  t349 = ((((t226 + t349_tmp * -0.261336621) - t268) + t272) + t291) + t293;
  t357 = ((((t4 - t87) + t18) + t33) + t20) + t22;
  t104 = ((((-t4 + t87) + t18) + t33) + t20) + t22;
  t22 = ((((t61 * t64 * 3.458 + t61 * (t77_tmp + 0.151149) * 3.458) +
           t137 * t151 * 3.458) +
          t144 * (t159 + 0.151149) * 3.458) +
         t241 * t259 * 3.458) +
        (t261_tmp + 0.151149) * t314_tmp * -3.458;
  t23 = t9 * t140_tmp;
  t154 = ((((t191 + t23 * -0.261336621) + t311) + t66) + t317) + t5;
  t87 = (t13 + 0.151149) * t314_tmp;
  t190 =
      ((((((((((t153 - t161) - t183) + t189) + t229) + t232) + t260) - t280) +
         t285) +
        t87 * -1.729) +
       t298) +
      t299;
  t18 = t9 * t256_tmp;
  t65 =
      ((((((((((t132 + t135) + t217) + t222) + t18 * 0.38038) + t245) + t249) +
          t262) +
         t32) +
        t306) +
       t315) +
      t24;
  t20 = ((((((((((-t132 - t135) + t217) + t222) + t18 * -0.38038) + t245) +
             t249) -
            t262) +
           t32) +
          t306) +
         t315) +
        t24;
  t18 = -(t3 * t61 * 0.38038) + t7 * t64 * 0.38038;
  t4 = (((((((((((((((t18 + t99) + t100) + b_t140_tmp * 0.38038) + t171) +
                  t179) -
                 t202) +
                t206) +
               t208) +
              t239) +
             t242) +
            b_t256_tmp * 1.729) +
           t276) +
          t25) +
         t34) +
        t51) +
       t314;
  t18 = (((((((((((((((t18 - t99) - t100) + b_t140_tmp * -0.38038) + t171) +
                   t179) -
                  t202) +
                 t206) -
                t208) +
               t239) +
              t242) +
             b_t256_tmp * -1.729) -
            t276) +
           t25) +
          t34) +
         t51) +
        t314;
  t34 = in2[0] * t18;
  t51 = in2[0] * t103;
  t52 = in2[0] * t357;
  t57 = in2[0] * t22;
  t58 = in2[0] * t20;
  t25 = ((((((-(t2 * t6 * 0.1673672) + t6 * (t10 + 0.151149) * 0.76076) -
             t48 * t61 * 3.458) +
            t45 * (t77_tmp + 0.151149) * 3.458) +
           t109 * (t159 + 0.151149) * 3.458) +
          t221 * (t261_tmp + 0.151149) * 3.458) +
         t259 * t256_tmp * 3.458) +
        t151 * t140_tmp * 3.458;
  t33 = ((t151 * (t159 + 0.151149) * 3.458 +
          t253 * (t261_tmp + 0.151149) * 3.458) +
         t259 * t285_tmp * 3.458) +
        t151 * t189_tmp * 3.458;
  S_tmp[0] = ((-in2[1] * t25 - in2[4] * t103) - in2[2] * t22) - in2[3] * t33;
  t24 = ((((-t191 + t311) + t66) + t317) + t5) + t23 * 0.261336621;
  S_tmp[1] = ((-in2[4] * t24 + in2[0] * t25) - in2[3] * t20) - in2[2] * t18;
  t32 =
      ((((((((((-t153 + t161) - t183) + t189) + t229) + t232) - t260) - t280) +
         t285) +
        t298) +
       t299) +
      t87 * 1.729;
  S_tmp[2] = ((t57 - in2[4] * t357) - in2[3] * t32) + in2[1] * t18;
  t23 = ((((-t226 - t268) + t272) + t291) + t293) + t349_tmp * 0.261336621;
  S_tmp[3] = ((-in2[4] * t23 + in2[1] * t20) + in2[2] * t32) + in2[0] * t33;
  S_tmp[4] = ((t51 + in2[3] * t23) + in2[1] * t24) + in2[2] * t357;
  S_tmp[5] = (((-in2[0] * t25 - in2[4] * t154) - in2[3] * t65) - in2[2] * t4) -
             in2[1] * ((((((t6 * 0.11498811324 + t152 * t256_tmp * 3.458) -
                           t7 * t48 * 0.76076) +
                          t45 * (t11 + 0.151149) * 3.458) +
                         t109 * (t78_tmp + 0.151149) * 3.458) +
                        (t160_tmp + 0.151149) * t221 * 3.458) +
                       t62 * t140_tmp * 3.458);
  t25 = ((((-(t3 * t7 * 0.1673672) + t7 * (t11 + 0.151149) * 0.76076) -
           t49 * t62 * 3.458) +
          t46 * (t78_tmp + 0.151149) * 3.458) +
         t110 * (t160_tmp + 0.151149) * 3.458) +
        t152 * t143_tmp * 3.458;
  t22 = t152 * (t160_tmp + 0.151149) * 3.458 + t152 * t190_tmp * 3.458;
  S_tmp[6] = (-in2[4] * t22 - in2[3] * t337) - in2[2] * t25;
  t20 = ((((((((((t86 - t96) + t101) + t102) + t143) - t172) - t180) + t203) -
           t207) +
          t209) -
         t240) -
        t243;
  t18 = ((((-t133 - t136) + t219) + t223) + t246) + t251;
  S_tmp[7] = ((t34 - in2[4] * t18) + in2[1] * t25) + in2[3] * t20;
  S_tmp[8] = ((t338 + t58) - in2[4] * t341) - in2[2] * t20;
  S_tmp[9] = ((in2[1] * t22 + in2[0] * t24) + in2[3] * t341) + in2[2] * t18;
  S_tmp[10] = (((-t57 - in2[4] * t104) - in2[3] * t190) - in2[1] * t4) -
              in2[2] * (((((t35 * 0.522673242 + t100_tmp * 0.11498811324) +
                           t8 * t137 * 0.76076) +
                          (t12 + 0.151149) * t144 * 3.458) +
                         t63 * t241 * 3.458) -
                        t131 * t314_tmp * 3.458);
  S_tmp[11] = (((-in2[1] * t25 - t34) - in2[4] * t344) - in2[3] * t353) -
              in2[2] * ((((t7 * 0.11498811324 - t8 * t49 * 0.76076) +
                          t46 * (t12 + 0.151149) * 3.458) +
                         t110 * t131 * 3.458) +
                        t63 * t143_tmp * 3.458);
  S_tmp[12] = -in2[4] * t271 + in2[3] * t307;
  S_tmp[13] = ((-t308 + -in2[1] * t20) + in2[4] * t332) + in2[0] * t32;
  S_tmp[14] = ((t273 + t52) - in2[3] * t332) + in2[1] * t18;
  S_tmp[15] =
      (((-in2[0] * t33 - in2[3] * (((t67 * 0.522673242 + t83 * 0.522673242) +
                                    t9 * t285_tmp * 0.76076) +
                                   (t13 + 0.151149) * t253 * 3.458)) -
        in2[4] * t349) -
       in2[2] * t190) -
      in2[1] * t65;
  S_tmp[16] = (((-t338 - t58) - in2[4] * t342) - in2[2] * t353) -
              in2[3] * (((t36 * 0.522673242 + t102_tmp * 0.11498811324) +
                         t9 * t138 * 0.76076) +
                        (t13 + 0.151149) * t145 * 3.458);
  S_tmp[17] = (((t308 + -in2[0] * t32) - in2[4] * t331) -
               in2[3] * ((t8 * 0.11498811324 - t9 * t50 * 0.76076) +
                         t47 * (t13 + 0.151149) * 3.458)) +
              in2[1] * t20;
  S_tmp[18] = in2[4] * t174;
  S_tmp[19] = ((-t178 - t333) + t343) + in2[0] * t23;
  S_tmp[20] = (((-t51 - in2[3] * t349) - in2[2] * t104) - in2[1] * t154) -
              in2[4] * (t163 * 0.522673242 + t177 * 0.522673242);
  S_tmp[21] =
      (((-in2[1] * t22 + -in2[0] * t24) - in2[3] * t342) - in2[2] * t344) -
      in2[4] * (t68 * 0.522673242 + t84 * 0.522673242);
  S_tmp[22] = (((-t273 + -in2[1] * t18) - t52) - in2[3] * t331) -
              in2[4] * (t37 * 0.522673242 + t104_tmp * 0.11498811324);
  S_tmp[23] =
      (((t178 + t333) - t343) + -in2[0] * t23) - in2[4] * t9 * 0.11498811324;
  S_tmp[24] = 0.0;
}

/* End of code generation (get_PlanarN_5_Snum.c) */
