/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_PlanarN_3_Mnum.c
 *
 * Code generation for function 'get_PlanarN_3_Mnum'
 *
 */

/* Include files */
#include "get_PlanarN_3_Mnum.h"

/* Function Definitions */
void get_PlanarN_3_Mnum(double in1[3], double M_INERTIA[9], double* S, double* C)
{
  double t14;
  double t18;
  double t2;
  double t22;
  double t25;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;

  /* get_PlanarN_3_Mnum */
  /*     M_INERTIA = get_PlanarN_3_Mnum(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     22-Jan-2025 16:27:53 */
  t2 = C[1]; //cos(in1[1]);
  t3 = C[2]; //cos(in1[2]);
  t4 = S[1]; //sin(in1[1]);
  t5 = S[2]; //sin(in1[2]);
  t6 = t2 * 0.22;
  t7 = t3 * 0.22;
  t18 = t3 * 0.11498811324;
  t3 *= t6 + 0.22;
  t14 = t4 * t7 + t5 * (t6 + 0.22);
  t25 = t4 * t5;
  t22 = (-(t25 * 0.22) + t3) + 0.151149;
  t25 = (-(t25 * 0.11498811324) + t3 * 0.522673242) + 0.407701537855058;
  t3 = ((t5 * t14 * 0.76076 + t2 * 0.11498811324) +
        (t7 + 0.151149) * t22 * 3.458) +
       0.736401537855058;
  M_INERTIA[0] =
      (((t4 * t4 * 0.1673672 + t14 * t14 * 3.458) + t22 * t22 * 3.458) +
       (t6 + 0.151149) * (t6 + 0.151149) * 3.458) +
      1.0651015378550579;
  M_INERTIA[1] = t3;
  M_INERTIA[2] = t25;
  M_INERTIA[3] = t3;
  M_INERTIA[4] =
      (t5 * t5 * 0.1673672 + (t7 + 0.151149) * (t7 + 0.151149) * 3.458) +
      0.736401537855058;
  M_INERTIA[5] = t18 + 0.407701537855058;
  M_INERTIA[6] = t25;
  M_INERTIA[7] = t18 + 0.407701537855058;
  M_INERTIA[8] = 0.407701537855058;
}

/* End of code generation (get_PlanarN_3_Mnum.c) */
