/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_Kukagnum.c
 *
 * Code generation for function 'get_Kukagnum'
 *
 */

/* Include files */
#include "get_Kukagnum.h"

/* Function Definitions */
void get_Kukagnum(double in1[7], double g_tmp[7], double S[7], double C[7])
{
  double g_tmp_tmp;
  double g_tmp_tmp_tmp;
  double g_tmp_tmp_tmp_tmp;
  double t10;
  double t11;
  double t12;
  double t13;
  double t14;
  double t15;
  double t16;
  double t17;
  double t18;
  double t18_tmp;
  double t19;
  double t2;
  double t20;
  double t21;
  double t22;
  double t23;
  double t24;
  double t25;
  double t25_tmp;
  double t26;
  double t26_tmp;
  double t27;
  double t28;
  double t29;
  double t3;
  double t32;
  double t36;
  double t38;
  double t39;
  double t4;
  double t40;
  double t41;
  double t44;
  double t45;
  double t46;
  double t47;
  double t48;
  double t49;
  double t5;
  double t51;
  double t52;
  double t54;
  double t55;
  double t59;
  double t6;
  double t60;
  double t61;
  double t62;
  double t63;
  double t7;
  double t8;
  double t9;
  /* get_Kukagnum */
  /*     G_TMP = get_Kukagnum(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     17-Dec-2024 17:37:53 */
  t2 = C[1]; //cos(in1[1]);
  t3 = C[2]; //cos(in1[2]);
  t4 = C[3]; //cos(in1[3]);
  t5 = C[4]; //cos(in1[4]);
  t6 = C[5]; //cos(in1[5]);
  t7 = C[6]; //cos(in1[6]);
  t8 = S[1]; //sin(in1[1]);
  t9 = S[2]; //sin(in1[2]);
  t10 = S[3]; //sin(in1[3]);
  t11 = S[4]; //sin(in1[4]);
  t12 = S[5]; //sin(in1[5]);
  t13 = S[6]; //sin(in1[6]);
  t14 = t2 * t4;
  t15 = t2 * t10;
  t16 = t4 * t8;
  t17 = t8 * t10;
  t18_tmp = t8 * t9;
  t18 = t18_tmp * t11;
  t22 = t2 * t5 * t9;
  t23 = t3 * t5 * t8;
  t25_tmp = t2 * t9;
  t25 = t25_tmp * t11;
  t26_tmp = t3 * t8;
  t26 = t26_tmp * t11;
  t27 = t5 * t8 * t9;
  t19 = t3 * t14;
  t20 = t3 * t15;
  t21 = t3 * t16;
  t24 = t3 * t17;
  t28 = t5 * t9 * t16;
  t29 = t9 * t11 * t16;
  t32 = t9 * t12 * t17;
  t36 = t14 + t24;
  t4 = t17 + t19;
  t44 = t26 + t28;
  t38 = t15 - t21;
  t39 = t16 - t20;
  t40 = t5 * t4;
  t41 = t6 * t36;
  t4 *= t11;
  t10 = t12 * t36;
  t51 = t23 - t29;
  t52 = t6 * t44;
  t45 = t5 * t41;
  t46 = t5 * t38;
  t47 = t11 * t38;
  t48 = t12 * t38;
  t49 = t12 * t39;
  t54 = t22 + t4;
  t61 = t32 + t52;
  t55 = t18 + t46;
  t62 = t45 + t48;
  t59 = t6 * t55;
  t60 = t12 * t55;
  t63 = t41 + t60;
  g_tmp[0] = 0.0;
  g_tmp_tmp_tmp_tmp = t25 - t40;
  g_tmp_tmp_tmp = t6 * g_tmp_tmp_tmp_tmp;
  g_tmp_tmp = t49 + g_tmp_tmp_tmp;
  g_tmp[1] =
      ((((((((((((t2 * 0.43467171698249141 + t8 * -33.983039975152437) +
                 t16 * -13.20459794239973) +
                (t17 * 0.093666333382175393 + t19 * 0.093666333382175393)) +
               t20 * 13.20459794239973) +
              (t22 * -0.443626099421243 + t25 * 0.031535400772034247)) +
             (t40 * -0.031535400772034247 - t4 * 0.443626099421243)) +
            (t49 * -0.0052513041685999986 +
             t7 * g_tmp_tmp * 0.0085532611809015)) +
           (t13 * g_tmp_tmp * -0.0030515435376993 -
            t2 * t3 * 0.0230344245399464)) +
          t25_tmp * 0.0164620768174089) +
         t6 * t39 * -0.31390447048519021) +
        t7 * t54 * 0.0030515435376993) +
       (t13 * t54 * 0.0085532611809015 -
        g_tmp_tmp_tmp * 0.0052513041685999986)) +
      t12 * g_tmp_tmp_tmp_tmp * 0.31390447048519021;
  g_tmp[2] =
      ((((((((((t23 * -0.443626099421243 + t26 * 0.031535400772034247) +
               (t28 * 0.031535400772034247 + t29 * 0.443626099421243)) +
              (t32 * -0.0052513041685999986 - t52 * 0.0052513041685999986)) +
             (t26_tmp * 0.0164620768174089 + t18_tmp * 0.0230344245399464)) +
            t9 * t16 * -0.093666333382175393) +
           t9 * t17 * -13.20459794239973) +
          t12 * t44 * 0.31390447048519021) +
         t7 * t51 * 0.0030515435376993) +
        (t13 * t51 * 0.0085532611809015 + t7 * t61 * 0.0085532611809015)) +
       t13 * t61 * -0.0030515435376993) +
      t6 * t9 * t17 * -0.31390447048519021;
  g_tmp[3] =
      ((((((((((t14 * -0.093666333382175393 + t15 * -13.20459794239973) +
               t21 * 13.20459794239973) +
              (t24 * -0.093666333382175393 - t45 * 0.0052513041685999986)) +
             (t48 * -0.0052513041685999986 + t5 * t36 * 0.031535400772034247)) +
            t6 * t38 * -0.31390447048519021) +
           t11 * t36 * 0.443626099421243) +
          t5 * t10 * 0.31390447048519021) +
         t7 * t62 * 0.0085532611809015) +
        t13 * t62 * -0.0030515435376993) +
       t7 * t11 * t36 * -0.0030515435376993) +
      t11 * t13 * t36 * -0.0085532611809015;
  g_tmp_tmp = t27 - t47;
  g_tmp[4] = ((((((t18 * 0.443626099421243 + t27 * 0.031535400772034247) +
                  (t46 * 0.443626099421243 - t47 * 0.031535400772034247)) +
                 t7 * t55 * -0.0030515435376993) +
                (t13 * t55 * -0.0085532611809015 -
                 t6 * g_tmp_tmp * 0.0052513041685999986)) +
               t12 * g_tmp_tmp * 0.31390447048519021) +
              t6 * t7 * g_tmp_tmp * 0.0085532611809015) +
             t6 * t13 * g_tmp_tmp * -0.0030515435376993;
  g_tmp[5] = (((t41 * 0.0052513041685999986 - t10 * 0.31390447048519021) +
               (t59 * 0.31390447048519021 + t60 * 0.0052513041685999986)) +
              t7 * t63 * -0.0085532611809015) +
             t13 * t63 * 0.0030515435376993;
  t4 = t10 - t59;
  g_tmp[6] = ((t7 * g_tmp_tmp * 0.0085532611809015 +
               t13 * g_tmp_tmp * -0.0030515435376993) +
              t7 * t4 * 0.0030515435376993) +
             t13 * t4 * 0.0085532611809015;
}

/* End of code generation (get_Kukagnum.c) */
