/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_PlanarN_4_Mnum.c
 *
 * Code generation for function 'get_PlanarN_4_Mnum'
 *
 */

/* Include files */
#include "get_PlanarN_4_Mnum.h"

/* Function Definitions */
void get_PlanarN_4_Mnum(double in1[4], double M_INERTIA[16], double* S, double* C)
{
  double t10;
  double t13_tmp;
  double t19;
  double t2;
  double t20;
  double t23;
  double t24;
  double t26;
  double t28_tmp;
  double t29;
  double t3;
  double t37;
  double t4;
  double t45;
  double t46;
  double t5;
  double t51;
  double t58;
  double t6;
  double t61;
  double t7;
  double t8;
  double t9;
  /* get_PlanarN_4_Mnum */
  /*     M_INERTIA = get_PlanarN_4_Mnum(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     22-Jan-2025 13:37:31 */
  t2 = C[1]; //cos(in1[1]);
  t3 = C[2]; //cos(in1[2]);
  t4 = C[3]; //cos(in1[3]);
  t5 = S[1]; //sin(in1[1]);
  t6 = S[2]; //sin(in1[2]);
  t7 = S[3]; //sin(in1[3]);
  t8 = t2 * 0.22;
  t9 = t3 * 0.22;
  t10 = t4 * 0.22;
  t13_tmp = t5 * t6;
  t37 = t4 * 0.11498811324;
  t19 = t3 * (t8 + 0.22);
  t20 = t4 * (t9 + 0.22);
  t23 = t5 * t9 + t6 * (t8 + 0.22);
  t24 = t6 * t10 + t7 * (t9 + 0.22);
  t28_tmp = -(t13_tmp * 0.22) + t19;
  t61 = t6 * t7;
  t45 = (-(t61 * 0.22) + t20) + 0.151149;
  t26 = t7 * t23;
  t29 = t4 * (t28_tmp + 0.22);
  t58 = (-(t61 * 0.11498811324) + t20 * 0.522673242) + 0.407701537855058;
  t46 = t4 * t23 + t7 * (t28_tmp + 0.22);
  t3 = ((t7 * t24 * 0.76076 + t3 * 0.11498811324) +
        (t10 + 0.151149) * t45 * 3.458) +
       0.736401537855058;
  t51 = (-t26 + t29) + 0.151149;
  t4 = (-(t26 * 0.522673242) + t29 * 0.522673242) + 0.407701537855058;
  t61 =
      (((-(t13_tmp * 0.11498811324) + t19 * 0.522673242) + t7 * t46 * 0.76076) +
       (t10 + 0.151149) * t51 * 3.458) +
      0.736401537855058;
  t20 = ((((t6 * t23 * 0.76076 + t2 * 0.11498811324) + t24 * t46 * 3.458) +
          (t9 + 0.151149) * (t28_tmp + 0.151149) * 3.458) +
         t45 * t51 * 3.458) +
        1.0651015378550579;
  M_INERTIA[0] = (((((t5 * t5 * 0.1673672 + t23 * t23 * 3.458) +
                     (t28_tmp + 0.151149) * (t28_tmp + 0.151149) * 3.458) +
                    t46 * t46 * 3.458) +
                   t51 * t51 * 3.458) +
                  (t8 + 0.151149) * (t8 + 0.151149) * 3.458) +
                 1.3938015378550579;
  M_INERTIA[1] = t20;
  M_INERTIA[2] = t61;
  M_INERTIA[3] = t4;
  M_INERTIA[4] = t20;
  M_INERTIA[5] = (((t6 * t6 * 0.1673672 + t24 * t24 * 3.458) +
                   (t9 + 0.151149) * (t9 + 0.151149) * 3.458) +
                  t45 * t45 * 3.458) +
                 1.0651015378550579;
  M_INERTIA[6] = t3;
  M_INERTIA[7] = t58;
  M_INERTIA[8] = t61;
  M_INERTIA[9] = t3;
  M_INERTIA[10] =
      (t7 * t7 * 0.1673672 + (t10 + 0.151149) * (t10 + 0.151149) * 3.458) +
      0.736401537855058;
  M_INERTIA[11] = t37 + 0.407701537855058;
  M_INERTIA[12] = t4;
  M_INERTIA[13] = t58;
  M_INERTIA[14] = t37 + 0.407701537855058;
  M_INERTIA[15] = 0.407701537855058;
}

/* End of code generation (get_PlanarN_4_Mnum.c) */
