/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_PlanarN_6_Mnum.c
 *
 * Code generation for function 'get_PlanarN_6_Mnum'
 *
 */

/* Include files */
#include "get_PlanarN_6_Mnum.h"

/* Function Definitions */
void get_PlanarN_6_Mnum(double in1[6], double M_INERTIA[36], double* S, double* C)
{
  double t10;
  double t103;
  double t11;
  double t110_tmp;
  double t111_tmp;
  double t112;
  double t113;
  double t12;
  double t121;
  double t13;
  double t136;
  double t137;
  double t14;
  double t144_tmp;
  double t15;
  double t152;
  double t154;
  double t16;
  double t160;
  double t167;
  double t170;
  double t171;
  double t177;
  double t183;
  double t187;
  double t2;
  double t21_tmp;
  double t22_tmp;
  double t3;
  double t33;
  double t34;
  double t35;
  double t36;
  double t4;
  double t41;
  double t42;
  double t43;
  double t44;
  double t48;
  double t49;
  double t5;
  double t50;
  double t54_tmp;
  double t55_tmp;
  double t56_tmp;
  double t57;
  double t58;
  double t59;
  double t6;
  double t7;
  double t75;
  double t8;
  double t9;
  double t91;
  double t92;
  double t93;
  double t94;
  /* get_PlanarN_6_Mnum */
  /*     M_INERTIA = get_PlanarN_6_Mnum(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     22-Jan-2025 13:38:06 */
  t2 = C[1]; //cos(in1[1]);
  t3 = C[2]; //cos(in1[2]);
  t4 = C[3]; //cos(in1[3]);
  t5 = C[4]; //cos(in1[4]);
  t6 = C[5]; //cos(in1[5]);
  t7 = S[1]; //sin(in1[1]);
  t8 = S[2]; //sin(in1[2]);
  t9 = S[3]; //sin(in1[3]);
  t10 = S[4]; //sin(in1[4]);
  t11 = S[5]; //sin(in1[5]);
  t12 = t2 * 0.22;
  t13 = t3 * 0.22;
  t14 = t4 * 0.22;
  t15 = t5 * 0.22;
  t16 = t6 * 0.22;
  t21_tmp = t7 * t8;
  t22_tmp = t8 * t9;
  t187 = t9 * t10;
  t75 = t6 * 0.11498811324;
  t33 = t3 * (t12 + 0.22);
  t34 = t4 * (t13 + 0.22);
  t35 = t5 * (t14 + 0.22);
  t36 = t6 * (t15 + 0.22);
  t41 = t7 * t13 + t8 * (t12 + 0.22);
  t42 = t8 * t14 + t9 * (t13 + 0.22);
  t43 = t9 * t15 + t10 * (t14 + 0.22);
  t44 = t10 * t16 + t11 * (t15 + 0.22);
  t54_tmp = -(t21_tmp * 0.22) + t33;
  t55_tmp = -(t22_tmp * 0.22) + t34;
  t56_tmp = -(t187 * 0.22) + t35;
  t113 = t10 * t11;
  t91 = (-(t113 * 0.22) + t36) + 0.151149;
  t48 = t9 * t41;
  t49 = t10 * t42;
  t50 = t11 * t43;
  t57 = t4 * (t54_tmp + 0.22);
  t58 = t5 * (t55_tmp + 0.22);
  t59 = t6 * (t56_tmp + 0.22);
  t152 = (-(t113 * 0.11498811324) + t36 * 0.522673242) + 0.407701537855058;
  t92 = t4 * t41 + t9 * (t54_tmp + 0.22);
  t93 = t5 * t42 + t10 * (t55_tmp + 0.22);
  t94 = t6 * t43 + t11 * (t56_tmp + 0.22);
  t167 = ((t11 * t44 * 0.76076 + t5 * 0.11498811324) +
          (t16 + 0.151149) * t91 * 3.458) +
         0.736401537855058;
  t103 = t10 * t92;
  t36 = t11 * t93;
  t110_tmp = -t48 + t57;
  t111_tmp = -t49 + t58;
  t121 = (-t50 + t59) + 0.151149;
  t112 = t5 * (t110_tmp + 0.22);
  t113 = t6 * (t111_tmp + 0.22);
  t160 = (-(t50 * 0.522673242) + t59 * 0.522673242) + 0.407701537855058;
  t136 = t5 * t92 + t10 * (t110_tmp + 0.22);
  t137 = t6 * t93 + t11 * (t111_tmp + 0.22);
  t144_tmp = -t103 + t112;
  t154 = (-t36 + t113) + 0.151149;
  t177 =
      (((-(t187 * 0.11498811324) + t35 * 0.522673242) + t11 * t94 * 0.76076) +
       (t16 + 0.151149) * t121 * 3.458) +
      0.736401537855058;
  t183 = ((((t10 * t43 * 0.76076 + t4 * 0.11498811324) + t44 * t94 * 3.458) +
           (t15 + 0.151149) * (t56_tmp + 0.151149) * 3.458) +
          t91 * t121 * 3.458) +
         1.0651015378550579;
  t50 = t11 * t136;
  t59 = t6 * (t144_tmp + 0.22);
  t170 = (-(t36 * 0.522673242) + t113 * 0.522673242) + 0.407701537855058;
  t171 = t6 * t136 + t11 * (t144_tmp + 0.22);
  t6 = (((-(t49 * 0.522673242) + t58 * 0.522673242) + t11 * t137 * 0.76076) +
        (t16 + 0.151149) * t154 * 3.458) +
       0.736401537855058;
  t4 = (((((-(t22_tmp * 0.11498811324) + t34 * 0.522673242) +
           t10 * t93 * 0.76076) +
          (t15 + 0.151149) * (t111_tmp + 0.151149) * 3.458) +
         t44 * t137 * 3.458) +
        t91 * t154 * 3.458) +
       1.0651015378550579;
  t187 = ((((((t9 * t42 * 0.76076 + t3 * 0.11498811324) + t43 * t93 * 3.458) +
             (t14 + 0.151149) * (t55_tmp + 0.151149) * 3.458) +
            (t56_tmp + 0.151149) * (t111_tmp + 0.151149) * 3.458) +
           t94 * t137 * 3.458) +
          t121 * t154 * 3.458) +
         1.3938015378550579;
  t35 = (-t50 + t59) + 0.151149;
  t5 = (-(t50 * 0.522673242) + t59 * 0.522673242) + 0.407701537855058;
  t59 = (((-(t103 * 0.522673242) + t112 * 0.522673242) + t11 * t171 * 0.76076) +
         (t16 + 0.151149) * t35 * 3.458) +
        0.736401537855058;
  t50 = (((((-(t48 * 0.522673242) + t57 * 0.522673242) + t10 * t136 * 0.76076) +
           (t15 + 0.151149) * (t144_tmp + 0.151149) * 3.458) +
          t44 * t171 * 3.458) +
         t91 * t35 * 3.458) +
        1.0651015378550579;
  t113 = (((((((-(t21_tmp * 0.11498811324) + t33 * 0.522673242) +
               t9 * t92 * 0.76076) +
              (t14 + 0.151149) * (t110_tmp + 0.151149) * 3.458) +
             t43 * t136 * 3.458) +
            (t56_tmp + 0.151149) * (t144_tmp + 0.151149) * 3.458) +
           t94 * t171 * 3.458) +
          t121 * t35 * 3.458) +
         1.3938015378550579;
  t36 = ((((((((t8 * t41 * 0.76076 + t2 * 0.11498811324) + t42 * t92 * 3.458) +
              (t13 + 0.151149) * (t54_tmp + 0.151149) * 3.458) +
             (t55_tmp + 0.151149) * (t110_tmp + 0.151149) * 3.458) +
            t93 * t136 * 3.458) +
           (t111_tmp + 0.151149) * (t144_tmp + 0.151149) * 3.458) +
          t137 * t171 * 3.458) +
         t154 * t35 * 3.458) +
        1.7225015378550581;
  M_INERTIA[0] = (((((((((t7 * t7 * 0.1673672 + t41 * t41 * 3.458) +
                         (t54_tmp + 0.151149) * (t54_tmp + 0.151149) * 3.458) +
                        t92 * t92 * 3.458) +
                       (t110_tmp + 0.151149) * (t110_tmp + 0.151149) * 3.458) +
                      t136 * t136 * 3.458) +
                     (t144_tmp + 0.151149) * (t144_tmp + 0.151149) * 3.458) +
                    t171 * t171 * 3.458) +
                   t35 * t35 * 3.458) +
                  (t12 + 0.151149) * (t12 + 0.151149) * 3.458) +
                 2.0512015378550581;
  M_INERTIA[1] = t36;
  M_INERTIA[2] = t113;
  M_INERTIA[3] = t50;
  M_INERTIA[4] = t59;
  M_INERTIA[5] = t5;
  M_INERTIA[6] = t36;
  M_INERTIA[7] = (((((((t8 * t8 * 0.1673672 + t42 * t42 * 3.458) +
                       (t13 + 0.151149) * (t13 + 0.151149) * 3.458) +
                      (t55_tmp + 0.151149) * (t55_tmp + 0.151149) * 3.458) +
                     t93 * t93 * 3.458) +
                    (t111_tmp + 0.151149) * (t111_tmp + 0.151149) * 3.458) +
                   t137 * t137 * 3.458) +
                  t154 * t154 * 3.458) +
                 1.7225015378550581;
  M_INERTIA[8] = t187;
  M_INERTIA[9] = t4;
  M_INERTIA[10] = t6;
  M_INERTIA[11] = t170;
  M_INERTIA[12] = t113;
  M_INERTIA[13] = t187;
  M_INERTIA[14] = (((((t9 * t9 * 0.1673672 + t43 * t43 * 3.458) +
                      (t14 + 0.151149) * (t14 + 0.151149) * 3.458) +
                     (t56_tmp + 0.151149) * (t56_tmp + 0.151149) * 3.458) +
                    t94 * t94 * 3.458) +
                   t121 * t121 * 3.458) +
                  1.3938015378550579;
  M_INERTIA[15] = t183;
  M_INERTIA[16] = t177;
  M_INERTIA[17] = t160;
  M_INERTIA[18] = t50;
  M_INERTIA[19] = t4;
  M_INERTIA[20] = t183;
  M_INERTIA[21] = (((t10 * t10 * 0.1673672 + t44 * t44 * 3.458) +
                    (t15 + 0.151149) * (t15 + 0.151149) * 3.458) +
                   t91 * t91 * 3.458) +
                  1.0651015378550579;
  M_INERTIA[22] = t167;
  M_INERTIA[23] = t152;
  M_INERTIA[24] = t59;
  M_INERTIA[25] = t6;
  M_INERTIA[26] = t177;
  M_INERTIA[27] = t167;
  M_INERTIA[28] =
      (t11 * t11 * 0.1673672 + (t16 + 0.151149) * (t16 + 0.151149) * 3.458) +
      0.736401537855058;
  M_INERTIA[29] = t75 + 0.407701537855058;
  M_INERTIA[30] = t5;
  M_INERTIA[31] = t170;
  M_INERTIA[32] = t160;
  M_INERTIA[33] = t152;
  M_INERTIA[34] = t75 + 0.407701537855058;
  M_INERTIA[35] = 0.407701537855058;
}

/* End of code generation (get_PlanarN_6_Mnum.c) */
