/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * get_PlanarN_4_Snum.c
 *
 * Code generation for function 'get_PlanarN_4_Snum'
 *
 */

/* Include files */
#include "get_PlanarN_4_Snum.h"

/* Function Definitions */
void get_PlanarN_4_Snum(double in1[4], double in2[4], double S_tmp[16], double* S, double* C)
{
  double t10;
  double t100;
  double t101;
  double t107;
  double t107_tmp;
  double t114;
  double t116;
  double t117;
  double t121;
  double t122;
  double t129;
  double t137;
  double t138;
  double t14;
  double t142;
  double t143;
  double t146;
  double t147;
  double t148;
  double t16;
  double t17;
  double t18;
  double t2;
  double t23;
  double t24;
  double t25;
  double t26;
  double t3;
  double t32;
  double t33;
  double t34;
  double t35;
  double t36;
  double t39;
  double t4;
  double t41;
  double t42;
  double t43;
  double t45;
  double t5;
  double t50_tmp;
  double t53;
  double t54;
  double t55;
  double t6;
  double t61;
  double t64;
  double t65;
  double t65_tmp;
  double t66;
  double t67;
  double t67_tmp;
  double t7;
  double t70;
  double t8;
  double t81;
  double t82;
  double t83;
  double t84;
  double t86;
  double t86_tmp;
  double t87;
  double t9;
  double t90;
  double t91;
  double t93_tmp;
  double t94;
  double t96;
  double t98;
  /* get_PlanarN_4_Snum */
  /*     S_tmp = get_PlanarN_4_Snum(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     22-Jan-2025 13:37:33 */
  t2 = C[1]; //cos(in1[1]);
  t3 = C[2]; //cos(in1[2]);
  t4 = C[3]; //cos(in1[3]);
  t5 = S[1]; //sin(in1[1]);
  t6 = S[2]; //sin(in1[2]);
  t7 = S[3]; //sin(in1[3]);
  t8 = t2 * 0.22;
  t9 = t3 * 0.22;
  t10 = t4 * 0.22;
  t17 = t5 * t6 * 0.22;
  t18 = t6 * t7 * 0.22;
  t64 = t2 * t6 * 0.05749405662;
  t65_tmp = t3 * t5;
  t65 = t65_tmp * 0.05749405662;
  t66 = t3 * t7 * 0.05749405662;
  t67_tmp = t4 * t6;
  t67 = t67_tmp * 0.05749405662;
  t14 = t5 * t9;
  t16 = t6 * t10;
  t23 = t3 * (t8 + 0.22);
  t24 = t4 * (t9 + 0.22);
  t25 = t6 * (t8 + 0.22);
  t26 = t7 * (t9 + 0.22);
  t32 = t6 * t8 + t14;
  t33 = t7 * t9 + t16;
  t34 = t3 * t8 - t17;
  t35 = t4 * t9 - t18;
  t36 = t4 * t32;
  t39 = t7 * t34;
  t41 = t14 + t25;
  t42 = t16 + t26;
  t50_tmp = -t17 + t23;
  t81 = (-t18 + t24) + 0.151149;
  t43 = t17 - t23;
  t17 = t18 - t24;
  t45 = t4 * t41;
  t14 = t7 * t41;
  t16 = t4 * (t50_tmp + 0.22);
  t53 = t7 * (t50_tmp + 0.22);
  t54 = t3 * t41 * 0.38038;
  t55 = t4 * t42 * 0.38038;
  t70 = t36 + t39;
  t82 = t36 * 0.261336621;
  t83 = t39 * 0.261336621;
  t86_tmp = t7 * t32 - t4 * t34;
  t86 = t7 * t86_tmp * 0.38038;
  t96 = t6 * (t50_tmp + 0.151149) * 0.38038;
  t18 = t7 * t81 * 0.38038;
  t98 = t4 * t7 * 0.1673672 - t7 * (t10 + 0.151149) * 0.76076;
  t101 = t41 * (t9 + 0.151149) * 1.729;
  t24 = t42 * (t10 + 0.151149) * 1.729;
  t23 = t7 * t43;
  t61 = t6 * t43 * 0.38038;
  t36 = t7 * t17 * 0.38038;
  t90 = t45 + t53;
  t91 = t45 * 0.261336621;
  t100 = in2[2] * t98;
  t107_tmp = t14 - t16;
  t107 = t7 * t107_tmp * 0.38038;
  t117 = (t10 + 0.151149) * t70 * 1.729;
  t122 = t42 * t107_tmp * 1.729;
  t84 = t14 + t4 * t43;
  t93_tmp = -t14 + t16;
  t94 = t23 * 0.261336621;
  t39 = t4 * t90 * 0.38038;
  t114 = t35 * t90 * 1.729;
  t121 = t17 * t90 * 1.729;
  t4 = (t10 + 0.151149) * t90 * 1.729;
  t129 = t81 * t90 * 1.729;
  t137 = t42 * t17 * 3.458 + t42 * t81 * 3.458;
  t142 = ((t3 * t6 * 0.1673672 - t6 * (t9 + 0.151149) * 0.76076) +
          t35 * t42 * 3.458) -
         t33 * t81 * 3.458;
  t146 = ((((-t55 + t36) + t66) + t67) + t18) + t24;
  t87 = t45 - t23;
  t116 = t42 * t84 * 1.729;
  t138 = in2[1] * t137;
  t143 = in2[1] * t142;
  t147 = ((((t55 - t36) + t66) + t67) - t18) - t24;
  t14 = t7 * (t93_tmp + 0.151149) * 0.38038;
  t3 = t33 * (t93_tmp + 0.151149) * 1.729;
  t55 = t81 * t87 * 1.729;
  t66 = t42 * (t93_tmp + 0.151149) * 1.729;
  t148 = in2[1] * t147;
  t16 = ((t41 * t43 * 3.458 + t41 * (t50_tmp + 0.151149) * 3.458) +
         t84 * t90 * 3.458) +
        t87 * (t93_tmp + 0.151149) * 3.458;
  t67 = ((((-t91 + t94) - t39) + t107) + t14) + t4;
  t18 = ((((t91 - t94) - t39) + t107) + t14) + t4;
  t24 = ((((t82 + t83) + t121) + t122) + t129) + t66;
  t36 = ((((((((((-t54 + t61) + t64) + t65) + t86) + t96) + t101) - t114) +
           t116) +
          t117) +
         t3) +
        t55;
  t39 = in2[0] * t16;
  t4 = in2[0] * t67;
  t23 = ((((-(t2 * t5 * 0.1673672) + t5 * (t8 + 0.151149) * 0.76076) -
           t34 * t41 * 3.458) +
          t32 * (t50_tmp + 0.151149) * 3.458) +
         t70 * (t93_tmp + 0.151149) * 3.458) +
        t90 * t86_tmp * 3.458;
  t17 = t90 * (t93_tmp + 0.151149) * 3.458 + t90 * t107_tmp * 3.458;
  S_tmp[0] = (-in2[3] * t17 - in2[2] * t16) - in2[1] * t23;
  t16 =
      ((((((((((t54 - t61) + t64) + t65) + t86) - t96) - t101) + t114) - t116) +
        t117) -
       t3) -
      t55;
  t14 = ((((-t82 - t83) + t121) + t122) + t129) + t66;
  S_tmp[1] = (-in2[3] * t14 + in2[0] * t23) + in2[2] * t16;
  S_tmp[2] = (t39 - in2[3] * t67) - in2[1] * t16;
  S_tmp[3] = (in2[0] * t17 + in2[2] * t67) + in2[1] * t14;
  S_tmp[4] = ((-in2[0] * t23 - in2[3] * t24) - in2[2] * t36) -
             in2[1] * ((((t5 * 0.11498811324 - t6 * t34 * 0.76076) +
                         t32 * (t9 + 0.151149) * 3.458) +
                        t70 * t81 * 3.458) +
                       t42 * t86_tmp * 3.458);
  S_tmp[5] = -in2[3] * t137 + in2[2] * t142;
  S_tmp[6] = (-t143 + -in2[0] * t16) + in2[3] * t147;
  S_tmp[7] = (t138 - in2[2] * t147) + in2[0] * t14;
  S_tmp[8] = ((-t39 - in2[3] * t18) - in2[1] * t36) -
             in2[2] * (((t25 * 0.522673242 + t65_tmp * 0.11498811324) +
                        t7 * t84 * 0.76076) +
                       (t10 + 0.151149) * t87 * 3.458);
  S_tmp[9] = ((t143 - in2[3] * t146) -
              in2[2] * ((t6 * 0.11498811324 - t7 * t35 * 0.76076) +
                        t33 * (t10 + 0.151149) * 3.458)) +
             in2[0] * t16;
  S_tmp[10] = in2[3] * t98;
  S_tmp[11] = (-t100 - t148) + t4;
  S_tmp[12] = ((-in2[0] * t17 - in2[2] * t18) - in2[1] * t24) -
              in2[3] * (t45 * 0.522673242 + t53 * 0.522673242);
  S_tmp[13] = ((-t138 + -in2[0] * t14) - in2[2] * t146) -
              in2[3] * (t26 * 0.522673242 + t67_tmp * 0.11498811324);
  S_tmp[14] = ((t100 + t148) - t4) - in2[3] * t7 * 0.11498811324;
  S_tmp[15] = 0.0;
}

/* End of code generation (get_PlanarN_4_Snum.c) */
