
% Coded by Giammarco Tonti 2025

% Make file that compiles all C files for the residuals_NE MEX file

clc

fprintf('** building residuals_NE mex file\n');

tic

mex -output residuals_NE residuals_NE.c ne.c ne_ext.c vmath_ext.c ...
                         some_robot_C_stuff/get_KukaMnum.c ...
                         some_robot_C_stuff/get_KukaSnum.c ...
                         some_robot_C_stuff/get_Kukagnum.c ... 
                         some_robot_C_stuff/frne_KUKAlwr4_num.c ...
                         some_robot_C_stuff/frne_ext_KUKAlwr4_num.c ...
                         some_robot_C_stuff/frne_PlanarN_num.c ...
                         some_robot_C_stuff/frne_ext_PlanarN_num.c ...
                         some_robot_C_stuff/get_PlanarN_3_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_3_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_4_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_4_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_5_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_5_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_6_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_6_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_7_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_7_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_8_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_8_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_9_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_9_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_10_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_10_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_11_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_11_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_12_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_12_Snum.c ...
                         some_robot_C_stuff/get_PlanarN_13_Mnum.c ...
                         some_robot_C_stuff/get_PlanarN_13_Snum.c ...
                         some_robot_C_stuff/dotMdotq_PlanarN_num.c ...
                         some_robot_C_stuff/dotMdotq_KUKAlwr4_num.c

toc

